# -*- coding: utf-8 -*-
"""MiniProjectDataScience.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g_bCLehmq6RtZ3k2Qn44ELZYjxSsP1hA
"""

#Q1 : What is the rate between Male to Female that participate at the olympic ?

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv(r'/content/Q1 rate.csv')
print(df)

plt.title("Rate between Male and Female")
plt.ylabel("Count")
Gender = ['Male', 'Female']
explode = (0.01, 0.01)
count = [50942, 18015]
plt.pie(count, labels = Gender, autopct='%1.1f%%', pctdistance=0.85, explode=explode)

centre_circle = plt.Circle((0, 0), 0.70, fc='white')
fig = plt.gcf()

fig.gca().add_artist(centre_circle)

#Q2 : What is number of participants per year ?

df_Name = pd.read_csv("dataset_olympics.csv")
Dup_Rows = df_Name[df_Name.duplicated()]

DF_RM_DUP = df_Name.drop_duplicates(subset='Name')
print('\n\nparticipants per year :\n', DF_RM_DUP.head(n=7000))

#Q3 : What is the most year participants win Gold Medal ?

gold_medal_winners = data[data['Medal'] == 'Gold']
most_gold_medal_year = gold_medal_winners.groupby('Year')['ID'].nunique().idxmax()
print("year in which most participants won gold medals:-", most_gold_medal_year)

#Q4 : What is higher sport that Sporter play it?

from collections import Counter
df = pd.read_csv("dataset_olympics.csv")
occurrences = Counter(df['Sport'])
most_used_word = max(occurrences, key=occurrences.get)
print("Sport that sportspersons played the most:-", most_used_word)